create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  nama text not null,
  kelas text not null,
  tanggal date not null,
  nominal numeric not null,
  bukti text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),

  constraint payments_status_check check (status in ('pending', 'valid', 'ditolak'))
);

create unique index if not exists payments_nama_kelas_unique
on public.payments (lower(nama), lower(kelas));

alter table public.payments enable row level security;

-- Karena backend memakai SERVICE_ROLE_KEY, backend tetap bisa insert/select/update/delete.
-- Jangan taruh SERVICE_ROLE_KEY di frontend/public/js.
